# Generated by Django 5.0.2 on 2024-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="author_pseudonym",
            field=models.CharField(
                blank=True,
                help_text="Enter author pseudonym (max 30 characters).",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Author Pseudonym",
            ),
        ),
    ]
