# Generated by Django 5.0.2 on 2024-02-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='displayed_identity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Displayed Identity'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='author_pseudonym',
            field=models.CharField(blank=True, help_text='Enter author pseudonym (max 100 characters).', max_length=100, null=True, unique=True, verbose_name='Author Pseudonym'),
        ),
    ]
