# Generated by Django 5.0.2 on 2024-02-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0005_remove_book_displayed_identity_book_displayed_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='displayed_name',
        ),
    ]
